use nginx-1.5.7 for security hole fixed

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -47,20 +47,20 @@ if [[ ! -f ${GLOBAL_DIR_OBJS}/http-parser-2.1/http_parser.h ]]; then echo "build
 if [[ ! -f ${GLOBAL_DIR_OBJS}/http-parser-2.1/libhttp_parser.a ]]; then echo "build http-parser-2.1 failed"; exit -1; fi
 
 # nginx for HLS, nginx-1.5.0
-if [[ -f ${GLOBAL_DIR_OBJS}/nginx-1.5.0/_release/sbin/nginx ]]; then
-    echo "nginx-1.5.0 is ok.";
+if [[ -f ${GLOBAL_DIR_OBJS}/nginx-1.5.7/_release/sbin/nginx ]]; then
+    echo "nginx-1.5.7 is ok.";
 else
-    echo "build nginx-1.5.0"; 
+    echo "build nginx-1.5.7"; 
     (
-        rm -rf ${GLOBAL_DIR_OBJS}/nginx-1.5.0 && cd ${GLOBAL_DIR_OBJS} && 
-        unzip -q ../3rdparty/nginx-1.5.0.zip && cd nginx-1.5.0 && 
+        rm -rf ${GLOBAL_DIR_OBJS}/nginx-1.5.7 && cd ${GLOBAL_DIR_OBJS} && 
+        unzip -q ../3rdparty/nginx-1.5.7.zip && cd nginx-1.5.7 && 
         ./configure --prefix=`pwd`/_release && make && make install &&
         ln -sf `pwd`/_release ../nginx
     )
 fi
 # check status
-ret=$?; if [[ $ret -ne 0 ]]; then echo "build nginx-1.5.0 failed, ret=$ret"; exit $ret; fi
-if [ ! -f ${GLOBAL_DIR_OBJS}/nginx-1.5.0/_release/sbin/nginx ]; then echo "build nginx-1.5.0 failed."; exit -1; fi
+ret=$?; if [[ $ret -ne 0 ]]; then echo "build nginx-1.5.7 failed, ret=$ret"; exit $ret; fi
+if [ ! -f ${GLOBAL_DIR_OBJS}/nginx-1.5.7/_release/sbin/nginx ]; then echo "build nginx-1.5.7 failed."; exit -1; fi
 
 # use current user to config nginx,
 # srs will write ts/m3u8 file use current user,
